general {
  # lock_cmd = pidof hyprlock || hyprlock
  lock_cmd = ~/.local/scripts/swaylock.sh
  before_sleep_cmd = loginctl lock-session
  #  after_sleep_cmd = hyprctl dispatch dpms on
  after_sleep_cmd = niri msg action-power-on
}

#listener {
#  timeout = 300                                  
#  on-timeout = brightnessctl -s set 10         
#  on-resume = brightnessctl -r                 
#}

listener {
  timeout = 350
  # on-timeout = loginctl lock-session
  on-timeout = niri msg action-do-screen-lock  # lock screen
}

listener {
  timeout = 400
  # on-timeout = hyprctl dispatch dpms off
  on-timeout = niri msg action-power-off       # turn off monitor
  # on-resume = hyprctl dispatch dpms on
  on-resume = niri msg action-power-on         # wake up monitor
}

# listener {
#   timeout = 1800
#   on-timeout = systemctl suspend
# }
